<script>
  import { GameData } from '$gameData';
  import Card from '$components/Card.svelte';
  import Modal from '$lib/components/Modal.svelte';
  import { CARD_CATEGORY_COLOR_MAP } from '$types';
  import { page } from '$app/stores';
  import { Languages } from '$lib/utils/types';

  // Toggles the drawer
  export let toggleDrawer;

  // Get the page data
  $: language = $page.data.language;
  $: isEn = language === Languages.ENGLISH;

  /** @type {import('$types').Card} */
  $: card = $page.data.cardData[$GameData.currentCardId];

  /**
   * 1-indexed round number
   * @type {number}
   */
  $: roundNum = $GameData.round + 1;

  /** Where or not to show the card's options */
  let showOptions = false;

  /** @type {import('$types').Option | null} */
  let displayedOption = null;

  const makeDecision = (optionId) => {
    // TODO: Handle invalid decision
    // GameData.advanceGameState({ optionId });
  };

  /**
   * Gets the text for how income is adjusted based on the salary update.
   *
   * @param {number | undefined} salaryUpdate
   * @return {string}
   */
  const getIncomeAdjustmentText = (salaryUpdate) => {
    if (!salaryUpdate) {
      return isEn ? "won't get any money" : 'no obtendrás dinero';
    }

    let updateText = isEn ? 'get' : 'obtendrás';
    if (salaryUpdate < 0) {
      salaryUpdate = -salaryUpdate;
      updateText = isEn ? 'stop earning' : 'dejarás de obtener';
    }

    if (isEn) {
      return `will ${updateText} <b>$${salaryUpdate}</b>`;
    }
    return `${updateText} <b>$${salaryUpdate}</b>`;
  };

  /**
   * Gets the text for how hours are adjusted based on the option update.
   *
   * @param {number | undefined} hoursUpdate
   * @return {string}
   */
  const getHoursAdjustmentText = (hoursUpdate) => {
    if (!hoursUpdate) {
      return isEn
        ? "won't have to work any additional hours"
        : 'no tendrás que trabajar horas adicionales';
    }

    if (hoursUpdate < 0) {
      return isEn
        ? `will work <b>${-hoursUpdate}</b> fewer hours every month`
        : `dejarás de trabajar <b>${-hoursUpdate}</b> horas cada mes`;
    }

    return isEn
      ? `will have to work <b>${hoursUpdate}</b> additional hours every month`
      : `tendrás que trabajar <b>${hoursUpdate}</b> horas adicionales cada mes`;
  };

  /**
   * Creates an autogenerated description that describes the options' updates.
   *
   * @param {import('$types').Option} option
   * @returns {string}
   */
  const stringifyOption = (option) => {
    if (!option) {
      return '';
    }

    const updates = option.updates;
    const incomeAdjustmentText = getIncomeAdjustmentText(updates.income?.salary);
    const hoursAdjustmentText = getHoursAdjustmentText(updates.time);

    let finalText =
      language == Languages.ENGLISH
        ? `If you choose this option you ${incomeAdjustmentText} and ${hoursAdjustmentText}`
        : `Si eliges esta opción, ${incomeAdjustmentText} y ${hoursAdjustmentText}`;
    if (option.except) {
      finalText += `, ${option.except}`;
    }

    return finalText + '.';
  };

  $: optionUpdatesDescription = stringifyOption(displayedOption);
  $: backgroundColor = showOptions
    ? `var(--light-${CARD_CATEGORY_COLOR_MAP[card.category]})`
    : 'transparent';
</script>

<Modal showModal={displayedOption}>
  <div class="implication-body" slot="body">
    <h3 style="margin-top:.2em;">{displayedOption?.description}</h3>
    <p style="margin-bottom:0;">{@html optionUpdatesDescription}</p>
    <p style="margin-top:0;">{@html displayedOption?.implicationText || ''}</p>
    <button on:click={() => makeDecision(displayedOption.id)} class="button">
      {#if isEn}Select{:else}Seleccionar{/if}
    </button>
  </div>
</Modal>
<Card {card} minimized={showOptions} onCardTap={() => (showOptions = !showOptions)} {roundNum} />
{#if showOptions}
  <h4 class="prompt">{card.prompt || ''}</h4>
  <ul>
    {#each card.options as option (option.id)}
      <li>
        <button class="button full-width" on:click={() => (displayedOption = option)}>
          {option.description}
        </button>
      </li>
    {/each}
  </ul>
{/if}
<div class="bg-color" style:background-color={backgroundColor} />

<style>
  .bg-color {
    position: fixed;
    inset: 0;
    z-index: -1;
    transition: background-color 200ms ease;
  }
  .implication-body {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .prompt {
    text-align: center;
  }

  ul {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 0 1rem;
  }
</style>
