<script>
  import cardData from '$gameFiles/card-data.json';
  import { GameData } from '$gameData';
  import Card from '$components/Card.svelte';
  import Modal from '$lib/components/Modal.svelte';
  import { CARD_CATEGORY_COLOR_MAP } from '$types';

  /** @type {import('$types').Card} */
  $: card = cardData[$GameData.currentCardId];

  /** Where or not to show the card's options */
  let showOptions = false;

  /** @type {import('$types').Option | null} */
  let displayedOption = null;

  const makeDecision = (optionId) => {
    // TODO: Handle invalid decision
    GameData.advanceGameState({ optionId });
  };

  /**
   * Creates an autogenerated description that describes the options' updates.
   *
   * @param {import('$types').Option} option
   * @returns {string}
   */
  const stringifyOption = (option) => {
    if (!option) {
      return '';
    }
    // FIXME: Update this based on specifications
    const updates = option.updates;
    return `If you choose this option you will get $${
      updates.money || 0
    } money and will have to work ${updates.time || 0} more hours.`;
  };

  $: optionUpdatesDescription = stringifyOption(displayedOption);
  $: backgroundColor = showOptions
    ? `var(--light-${CARD_CATEGORY_COLOR_MAP[card.category]})`
    : 'transparent';
</script>

<Modal showModal={displayedOption}>
  <div class="implication-body" slot="body">
    <h3>{displayedOption?.description}</h3>
    <p>{optionUpdatesDescription}</p>
    <p>Implication: {displayedOption?.implicationText}</p>
    <button on:click={() => makeDecision(displayedOption.id)} class="button">Select</button>
  </div>
</Modal>
<main style:background-color={backgroundColor}>
  <Card {card} minimized={showOptions} onCardTap={() => (showOptions = !showOptions)} />
  {#if showOptions}
    <h3 class="prompt">{card.prompt || 'MISSING PROMPT? 🥲'}</h3>
    <ul>
      {#each card.options as option (option.id)}
        <li>
          <button class="button button3" on:click={() => (displayedOption = option)}>
            {option.description}
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</main>

<style>
  main {
    width: 100vw;
    height: 100vh;
    margin-top: -20px;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;

    transition: background-color 200ms ease;
  }
  .implication-body {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .prompt {
    text-align: center;
  }

  ul {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
</style>
