<script>
  import { GameData } from '$gameData';
  import Card from '$components/Card.svelte';
  import Modal from '$lib/components/Modal.svelte';
  import { CARD_CATEGORY_COLOR_MAP, DRAWER_ANIM_DURATION, GameStates } from '$types';
  import { page } from '$app/stores';
  import { Languages } from '$lib/utils/types';
  import LearnMore from '$components/LearnMore.svelte';
  import wildCardsEn from '$gameFiles/wild-cards.json';
  import wildCardsEs from '$gameFiles/wild-cards-es.json';

  // Toggles the drawer
  export let toggleDrawer;

  // Get the page data
  $: language = $page.data.language;
  $: isEn = language === Languages.ENGLISH;

  /** @type {import('$types').Card} */
  $: wildCards = isEn ? wildCardsEn : wildCardsEs;
  let card,
    cardLoaded = false;
  $: if (!cardLoaded) {
    card = ($GameData.state === GameStates.WILD_CARD ? wildCards : $page.data.cardData)[
      $GameData.currentCardId
    ];
    cardLoaded = true;
  }

  /**
   * 1-indexed round number
   * @type {number}
   */
  $: roundNum = $GameData.round + 1;

  /** Where or not to show the card's options */
  let showOptions = false;

  /** @type {import('$types').Option | null} */
  let displayedOption = null;

  const makeDecision = (optionId) => {
    // Close the option modal
    displayedOption = null;

    // Open drawer for animation
    toggleDrawer();
    const optionUpdates = card.options.find((option) => option.id === optionId).updates;
    // Start animation when the drawer is fully up
    setTimeout(() => {
      GameData.resourceUpdater($GameData.resources, optionUpdates).then(() => {
        // Close drawer and advance game state after animations are finished
        toggleDrawer();
        setTimeout(() => {
          GameData.advanceGameState({ optionId });
        }, DRAWER_ANIM_DURATION);
      });
    }, DRAWER_ANIM_DURATION);
  };

  /**
   * Gets the text for how income is adjusted based on the salary update.
   *
   * @param {number | undefined} salaryUpdate
   * @return {string}
   */
  const getIncomeAdjustmentText = (salaryUpdate) => {
    if (!salaryUpdate) {
      return isEn ? 'will stay the same.' : 'permanecerán iguales.';
    }

    let updateText = isEn ? 'have increased by' : 'recursos económicos han aumentado';
    if (salaryUpdate < 0) {
      salaryUpdate = -salaryUpdate;
      updateText = isEn ? 'have decreased by' : 'recursos económicos han disminuido';
    }

    if (isEn) {
      return `will ${updateText} <b>$${salaryUpdate}</b>`;
    }
    return `${updateText} <b>$${salaryUpdate}</b>`;
  };

  /**
   * Gets the text for how hours are adjusted based on the option update.
   *
   * @param {number | undefined} hoursUpdate
   * @return {string}
   */
  const getHoursAdjustmentText = (hoursUpdate) => {
    if (!hoursUpdate) {
      return isEn
        ? 'the number of hours spent on work and obligations will stay the same.'
        : 'el número de horas dedicadas a trabajo y obligaciones permanecerán iguales.';
    }

    if (hoursUpdate < 0) {
      return isEn
        ? `the number of hours dedicated to work and obligations will be reduced by <b>${-hoursUpdate}</b> hours every week.`
        : `el número de horas dedicadas a trabajo y obligaciones se reducirá en <b>${-hoursUpdate}</b> horas cada semana.`;
    }

    return isEn
      ? `the number of hours dedicated to work and obligations will increase by <b>${hoursUpdate}</b> hours every week.`
      : `el número de horas dedicadas al trabajo y obligaciones aumentará <b>${hoursUpdate}</b> horas cada semana.`;
  };

  /**
   * Creates an autogenerated description that describes the options' updates.
   *
   * @param {import('$types').Option} option
   * @returns {string}
   */
  const stringifyOption = (option) => {
    if (!option) {
      return '';
    }

    const updates = option.updates;
    const incomeAdjustmentText = getIncomeAdjustmentText(updates.income?.salary);
    const hoursAdjustmentText = getHoursAdjustmentText(updates.time);

    let finalText = updates.income?.salary === -9999? (isEn ? 'By choosing this option you will have to look for a new job.' : 'Al elegir esta opción debes encontrar un nuevo empleo.') :
      (isEn ? `By chosing this option your economic resources ${incomeAdjustmentText} and ${hoursAdjustmentText}` : `Al elegir esta opción tus recursos económicos ${incomeAdjustmentText} y ${hoursAdjustmentText}.`);

    if (updates.income?.salary === 0.0) {
      finalText = ''; // Set finalText to an empty string
    }

    if (option.except) {
      finalText += `${option.except}`;
    }

    return finalText + ' ';
  };

  $: optionUpdatesDescription = stringifyOption(displayedOption);
  $: backgroundColor = showOptions
    ? `var(--light-${CARD_CATEGORY_COLOR_MAP[card.category]})`
    : 'transparent';
</script>

<Modal showModal={displayedOption}>
  <div class="implication-body" slot="body">
    <h3 style="margin-top:.2em;">{displayedOption?.description}</h3>
    <p style="margin-bottom:0;">{@html optionUpdatesDescription}</p>
    <p style="margin-top:0;"><br>{@html displayedOption?.implicationText || ''}</p>
    <button on:click={() => makeDecision(displayedOption.id)} class="button">
      {#if displayedOption?.updates.income?.salary === -9999}
        {#if isEn}Search for a new job{:else}Encontrar un nuevo empleo{/if}
      {:else}
        {#if isEn}Select{:else}Seleccionar{/if}
      {/if}
    </button>
  </div>
</Modal>
<Card {card} minimized={showOptions} onCardTap={() => (showOptions = !showOptions)} {roundNum} />
{#if showOptions}
  <div class="centered-column">
    <h4 class="prompt">{card.prompt || ''}</h4>
    {#if card.learn_more}
      <LearnMore>
        <h1 slot="title">{card.title}</h1>
        <p slot="body">{card.learn_more}</p>
      </LearnMore>
    {/if}
  </div>
  <ul>
    {#each card.options as option (option.id)}
      <li>
        <button class="button full-width" on:click={() => (displayedOption = option)}>
          {option.description}
        </button>
      </li>
    {/each}
  </ul>
{/if}
<div class="bg-color" style:background-color={backgroundColor} />

<style>
  .bg-color {
    position: fixed;
    inset: 0;
    z-index: -1;
    transition: background-color 200ms ease;
  }
  .implication-body {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .prompt {
    text-align: center;
    margin-top: 1rem;
  }

  ul {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 0 1rem;
    margin: 0;
    width: 100%;
  }

  button {
    padding-left: 1.5rem;
    padding-right: 1.5rem;
  }
</style>
